# golangci-lint configuration for golint-sl
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false # Type assertions on pass.ResultOf are safe in analyzers
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy for most projects

  gocyclo:
    min-complexity: 30 # Analyzer code tends to have higher complexity due to AST traversal

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/spechtlabs/golint-sl

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - ifElseChain
      - commentedOutCode

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  stylecheck:
    checks:
      - "all"
      - "-ST1000" # Package comments - handled by revive

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - gocyclo

    # Exclude testdata directory
    - path: testdata/
      linters:
        - all

    # Allow init functions in analyzer packages (common pattern)
    - path: ".*/analyzer\\.go$"
      linters:
        - gochecknoinits

    # Analyzer code often has stuttering type names for clarity (e.g., ReconcilerInfo in reconciler package)
    - path: ".*/analyzer\\.go$"
      linters:
        - revive
      text: "stutters"

    # Allow goconst issues in analyzer code (string literals are often clearer inline)
    - path: ".*/analyzer\\.go$"
      linters:
        - goconst

    # Allow gocritic suggestions in analyzer code (AST traversal patterns are idiomatic)
    - path: ".*/analyzer\\.go$"
      linters:
        - gocritic
      text: "singleCaseSwitch|typeAssertChain|nestingReduce|paramTypeCombine"

    # Prealloc suggestions are often not applicable in analyzer code
    - path: ".*/analyzer\\.go$"
      linters:
        - prealloc

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
