# golangci-lint configuration for golint-sl
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters (gosimple and stylecheck are now part of staticcheck)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gochecknoinits
    # Disabled: goconst - inline strings are clearer in analyzer code
    # Disabled: gocritic - too many style suggestions for AST code
    # Disabled: gocyclo - AST traversal code can be complex
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    # Disabled: prealloc - not critical for this codebase
    # Disabled: revive - too many false positives for analyzer code
    - rowserrcheck
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: false # Type assertions on pass.ResultOf are safe in analyzers
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy for most projects

  dupl:
    threshold: 100

  misspell:
    locale: US

  goimports:
    local-prefixes: github.com/spechtlabs/golint-sl

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - dupl
        - gosec

    # Exclude testdata directory
    - path: testdata/
      linters:
        - dupl
        - gosec
        - errcheck
        - govet
        - staticcheck

    # Allow init functions in analyzer packages (common pattern)
    - path: analyzer\.go
      linters:
        - gochecknoinits

    # Allow gosec G304 (file inclusion via variable) in config code
    - path: internal/config/
      linters:
        - gosec
      text: "G304"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
