- id: golint-sl
  name: golint-sl
  description: Build custom golangci-lint binary with golint-sl and run on all packages
  entry: bash -c 'golangci-lint custom && ./custom-gcl run ./...'
  language: system
  types: [go]
  pass_filenames: false

- id: golint-sl-pkg
  name: golint-sl (per package)
  description: Build custom golangci-lint binary with golint-sl and run on changed packages
  entry: bash -c 'golangci-lint custom && ./custom-gcl run'
  language: system
  types: [go]
  pass_filenames: true
  require_serial: true
