- id: golint-sl
  name: golint-sl
  description: Run golint-sl - 32 analyzers for Go best practices
  entry: golint-sl
  language: golang
  types: [go]
  pass_filenames: false
  args: ["./..."]

- id: golint-sl-pkg
  name: golint-sl (per package)
  description: Run golint-sl on changed packages only
  entry: golint-sl
  language: golang
  types: [go]
  pass_filenames: true
  require_serial: true
